const MOVIES_API_BASE_URL = "https://api.nomoreparties.co/beatfilm-movies";
const API_BASE_URL = "https://api.diplomtimush.nomoredomainsicu.ru";
// const API_BASE_URL = "http://localhost:3000";

const STATUS_SUCCESS = "success";
const STATUS_FAIL = "fail";

const SHORT_MOVIE_DURATION = 40;

const EMAIL_REGEX = "^\\S+@\\S+\\.\\S+$";
const NAME_REGEX = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";

const DESKTOP_MAX_RESOLUTION = 1280;
const DESKTOP_LAPTOP_RESOLUTION = 1024;
const TABLET_RESOLUTION = 768;
const MOBILE_RESOLUTION = 481;
const INIT_MAX_DESKTOP = 16;
const INIT_LAPTOP_DESKTOP = 12;
const INIT_TABLET = 8;
const INIT_MOBILE = 5;
const STEP_DESKTOP = 4;
const STEP_TABLET = 3;
const STEP_MOBILE = 2;

export {
  MOVIES_API_BASE_URL,
  API_BASE_URL,
  STATUS_SUCCESS,
  STATUS_FAIL,
  SHORT_MOVIE_DURATION,
  EMAIL_REGEX,
  NAME_REGEX,
  DESKTOP_MAX_RESOLUTION,
  DESKTOP_LAPTOP_RESOLUTION,
  TABLET_RESOLUTION,
  MOBILE_RESOLUTION,
  INIT_MAX_DESKTOP,
  INIT_LAPTOP_DESKTOP,
  INIT_TABLET,
  INIT_MOBILE,
  STEP_DESKTOP,
  STEP_TABLET,
  STEP_MOBILE,

}