import tempPoster from "../images/poster-test.jpg";
export const movies = [
  {
    id: 1,
    name: "tempName1 longer and longer and longer and longer and longer and longer and longer",
    image: tempPoster,
    duration: 31,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 2,
    name: "tempName2",
    image: tempPoster,
    duration: 32,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 3,
    name: "tempName3",
    image: tempPoster,
    duration: 33,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 4,
    name: "tempName4",
    image: tempPoster,
    duration: 34,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 5,
    name: "tempName5 longer and longer and longer and longer and longer and longer and longer",
    image: tempPoster,
    duration: 35,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 6,
    name: "tempName6",
    image: tempPoster,
    duration: 36,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 7,
    name: "tempName7",
    image: tempPoster,
    duration: 37,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 8,
    name: "tempName8",
    image: tempPoster,
    duration: 38,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 9,
    name: "tempName9",
    image: tempPoster,
    duration: 39,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 10,
    name: "tempName10",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 11,
    name: "tempName11",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 12,
    name: "tempName12",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 13,
    name: "tempName13",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 14,
    name: "tempName14",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 15,
    name: "tempName15",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 16,
    name: "tempName16",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 17,
    name: "tempName17",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 18,
    name: "tempName18",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 19,
    name: "tempName19",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 20,
    name: "tempName20",
    image: tempPoster,
    duration: 40,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
]

export const savedMovies = [
  {
    id: 1,
    name: "tempName1",
    image: tempPoster,
    duration: 31,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 2,
    name: "tempName2",
    image: tempPoster,
    duration: 32,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 3,
    name: "tempName3",
    image: tempPoster,
    duration: 33,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 4,
    name: "tempName4",
    image: tempPoster,
    duration: 34,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
  {
    id: 5,
    name: "tempName5",
    image: tempPoster,
    duration: 35,
    trailerLink: "https://www.youtube.com/watch?v=w0m2C3lN1h8",
  },
]